form:
    class: Silex\Provider\FormServiceProvider
    parameters:
        form.secret: REPLACE_THIS_NOT_SO_SECRET_SECRET

monolog:
    class: Silex\Provider\MonologServiceProvider
    parameters:
        monolog.level: 300
        monolog.logfile: "%path.logs%/%mode%.log"

translation:
    class: Herrera\Silex\Provider\TranslationServiceProvider
    parameters:
        locale: en
        locale_fallback: en
        translator.files:
            Symfony\Component\Translation\Loader\YamlFileLoader:
                "%path.translations%/example.de.yml": "de"
                "%path.translations%/example.en.yml": "en"
                "%path.translations%/example.fr.yml": "fr"

twig:
    class: Silex\Provider\TwigServiceProvider
    parameters:
        twig.path: "%path.views%"
        twig.options:
            auto_reload: %debug%
            cache: "%path.cache%/views"
            debug: %debug%

url_generator:
    class: Silex\Provider\UrlGeneratorServiceProvider

validator:
    class: Silex\Provider\ValidatorServiceProvider
